//
//  ShopItems.h
//  Clicker
//
//  Created by MacCoder on 5/10/14.
//  Copyright (c) 2014 MacCoder. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "ShopItem.h"
#import "GameConstants.h"

#define SHOP_ITEM_ID_ACTIVE_TIER_1 @"SHOP_ITEM_ID_ACTIVE_TIER_1"
#define SHOP_ITEM_ID_ACTIVE_TIER_2 @"SHOP_ITEM_ID_ACTIVE_TIER_2"
#define SHOP_ITEM_ID_ACTIVE_TIER_3 @"SHOP_ITEM_ID_ACTIVE_TIER_3"
#define SHOP_ITEM_ID_ACTIVE_TIER_4 @"SHOP_ITEM_ID_ACTIVE_TIER_4"
#define SHOP_ITEM_ID_ACTIVE_TIER_5 @"SHOP_ITEM_ID_ACTIVE_TIER_5"
#define SHOP_ITEM_ID_ACTIVE_TIER_6 @"SHOP_ITEM_ID_ACTIVE_TIER_6"
#define SHOP_ITEM_ID_ACTIVE_TIER_7 @"SHOP_ITEM_ID_ACTIVE_TIER_7"
#define SHOP_ITEM_ID_ACTIVE_TIER_8 @"SHOP_ITEM_ID_ACTIVE_TIER_8"
#define SHOP_ITEM_ID_ACTIVE_TIER_9 @"SHOP_ITEM_ID_ACTIVE_TIER_9"
#define SHOP_ITEM_ID_ACTIVE_TIER_10 @"SHOP_ITEM_ID_ACTIVE_TIER_10"

#define SHOP_ITEM_ID_PASSIVE_TIER_1 @"SHOP_ITEM_ID_PASSIVE_TIER_1"
#define SHOP_ITEM_ID_PASSIVE_TIER_2 @"SHOP_ITEM_ID_PASSIVE_TIER_2"
#define SHOP_ITEM_ID_PASSIVE_TIER_3 @"SHOP_ITEM_ID_PASSIVE_TIER_3"
#define SHOP_ITEM_ID_PASSIVE_TIER_4 @"SHOP_ITEM_ID_PASSIVE_TIER_4"
#define SHOP_ITEM_ID_PASSIVE_TIER_5 @"SHOP_ITEM_ID_PASSIVE_TIER_5"
#define SHOP_ITEM_ID_PASSIVE_TIER_6 @"SHOP_ITEM_ID_PASSIVE_TIER_6"
#define SHOP_ITEM_ID_PASSIVE_TIER_7 @"SHOP_ITEM_ID_PASSIVE_TIER_7"
#define SHOP_ITEM_ID_PASSIVE_TIER_8 @"SHOP_ITEM_ID_PASSIVE_TIER_8"
#define SHOP_ITEM_ID_PASSIVE_TIER_9 @"SHOP_ITEM_ID_PASSIVE_TIER_9"
#define SHOP_ITEM_ID_PASSIVE_TIER_10 @"SHOP_ITEM_ID_PASSIVE_TIER_10"

#define SHOP_ITEM_ID_OFFLINE_CAP_TIER_1 @"SHOP_ITEM_ID_OFFLINE_CAP_TIER_1"
#define SHOP_ITEM_ID_OFFLINE_CAP_TIER_2 @"SHOP_ITEM_ID_OFFLINE_CAP_TIER_2"
#define SHOP_ITEM_ID_OFFLINE_CAP_TIER_3 @"SHOP_ITEM_ID_OFFLINE_CAP_TIER_3"
#define SHOP_ITEM_ID_OFFLINE_CAP_TIER_4 @"SHOP_ITEM_ID_OFFLINE_CAP_TIER_4"
#define SHOP_ITEM_ID_OFFLINE_CAP_TIER_5 @"SHOP_ITEM_ID_OFFLINE_CAP_TIER_5"
#define SHOP_ITEM_ID_OFFLINE_CAP_TIER_6 @"SHOP_ITEM_ID_OFFLINE_CAP_TIER_6"
#define SHOP_ITEM_ID_OFFLINE_CAP_TIER_7 @"SHOP_ITEM_ID_OFFLINE_CAP_TIER_7"
#define SHOP_ITEM_ID_OFFLINE_CAP_TIER_8 @"SHOP_ITEM_ID_OFFLINE_CAP_TIER_8"
#define SHOP_ITEM_ID_OFFLINE_CAP_TIER_9 @"SHOP_ITEM_ID_OFFLINE_CAP_TIER_9"
#define SHOP_ITEM_ID_OFFLINE_CAP_TIER_10 @"SHOP_ITEM_ID_OFFLINE_CAP_TIER_10"

#define SHOP_ITEM_ID_OFFLINE_SPEED_TIER_1 @"SHOP_ITEM_ID_OFFLINE_SPEED_TIER_1"
#define SHOP_ITEM_ID_OFFLINE_SPEED_TIER_2 @"SHOP_ITEM_ID_OFFLINE_SPEED_TIER_2"
#define SHOP_ITEM_ID_OFFLINE_SPEED_TIER_3 @"SHOP_ITEM_ID_OFFLINE_SPEED_TIER_3"
#define SHOP_ITEM_ID_OFFLINE_SPEED_TIER_4 @"SHOP_ITEM_ID_OFFLINE_SPEED_TIER_4"
#define SHOP_ITEM_ID_OFFLINE_SPEED_TIER_5 @"SHOP_ITEM_ID_OFFLINE_SPEED_TIER_5"
#define SHOP_ITEM_ID_OFFLINE_SPEED_TIER_6 @"SHOP_ITEM_ID_OFFLINE_SPEED_TIER_6"
#define SHOP_ITEM_ID_OFFLINE_SPEED_TIER_7 @"SHOP_ITEM_ID_OFFLINE_SPEED_TIER_7"
#define SHOP_ITEM_ID_OFFLINE_SPEED_TIER_8 @"SHOP_ITEM_ID_OFFLINE_SPEED_TIER_8"
#define SHOP_ITEM_ID_OFFLINE_SPEED_TIER_9 @"SHOP_ITEM_ID_OFFLINE_SPEED_TIER_9"
#define SHOP_ITEM_ID_OFFLINE_SPEED_TIER_10 @"SHOP_ITEM_ID_OFFLINE_SPEED_TIER_10"

#define SHOP_ITEM_ID_IAP_DOUBLE_POINTS @"SHOP_ITEM_ID_IAP_DOUBLE_POINTS"
#define SHOP_ITEM_ID_IAD_QUDRUPLE_POINTS @"SHOP_ITEM_ID_IAD_QUDRUPLE_POINTS"
#define SHOP_ITEM_ID_IAD_SUPER_POINTS @"SHOP_ITEM_ID_IAD_SUPER_POINTS"
#define SHOP_ITEM_ID_IAP_FUND @"SHOP_ITEM_ID_IAP_FUND"
@interface ShopManager : NSObject

+ (ShopManager *)instance;
- (NSArray *)arrayOfitemIdsFor:(PowerUpType)type;
- (int) priceForItemId:(NSString *)itemId type:(PowerUpType)type;
- (ShopItem *)shopItemForItemId:(NSString *)itemId dictionary:(PowerUpType)type;

@end
